stages:
  - build
  - deploy

build:
  stage: build
  when: manual
  script:
    - docker-compose build
    - docker push antarcticmap/geoserver:2.18.2
  only:
    - master
  tags:
    - shell
    - build

deploy:
  stage: deploy
  when: manual
  script:
    - sed -i "s@__GEOSERVER_DATA_PATH__@$GEOSERVER_DATA_PATH@g" geoserver.yaml
    - sed -i "s@__DATA_PATH__@$DATA_PATH@g" geoserver.yaml
    - kubectl apply -f geoserver.yaml
    - kubectl apply -f ingressroute.yaml
  environment:
    name: production
    url: https://geo.freeyeti.net/
  only:
    - master
  tags:
    - shell
    - deploy
