stages:
  - deploy

deploy:
  stage: deploy
  script:
    - sed -i "s@__GEOSERVER_DATA_PATH__@$GEOSERVER_DATA_PATH@g" geoserver.yml
    - sed -i "s@__DATA_PATH__@$DATA_PATH@g" geoserver.yml
    - kubectl apply -f geoserver.yml 
  environment:
    name: production
    url: https://geoserver.freeyeti.net/
  only:
    - master
  tags:
    - shell
    - deploy
  