stages:
  - build
  - deploy

build:
  stage: build
  when: manual
  script:
    - docker-compose build
    - docker push antarcticmap/geoserver:2.18.1
  only:
    - master
  tags:
    - shell
    - deploy

deploy:
  stage: deploy
  when: manual
  script:
    - sed -i "s@__GEOSERVER_DATA_PATH__@$GEOSERVER_DATA_PATH@g" geoserver.yml
    - sed -i "s@__DATA_PATH__@$DATA_PATH@g" geoserver.yml
    - microk8s kubectl apply -f geoserver.yml
  environment:
    name: production
    url: https://geoserver.freeyeti.net/
  only:
    - master
  tags:
    - shell
    - deploy
