version: "3.8"

services:
  geoserver:
    build:
      context: .
      dockerfile: Dockerfile
    image: antarcticmap/geoserver:2.20.4
    ports:
      - "0.0.0.0:8080:8080"
    volumes:
      - ${GEOSERVER_DATA_PATH}:/data
      - ${DATA_PATH}:/geodata
    environment:
      - GEOSERVER_DATA_DIR=/data
