version: '3.8'

services:
  geoserver:
    build:
      context: .
      dockerfile: Dockerfile
    image: geoserver:latest
    ports:
      - "8080:8080"
    volumes:
      - ${DATA_PATH}:/data
    environment:
      - GEOSERVER_DATA_DIR=/data
